# Eventually we might want to limit this to any branch but the main branch
# and have the main branch workflow tag and release a new version
# for now the '**' matches any branch and pull request
name: Build any branch

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'
jobs:
  validation:
    name: Validate Gradle
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: gradle/wrapper-validation-action@v1
  build:
    runs-on: ubuntu-latest
    needs: [validation]
    permissions:
      contents: read
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: Run shadedJar with Gradle Wrapper
        uses: gradle/gradle-build-action@v2
        with:
          arguments: --no-daemon clean shadedJar
      - name: Artifact jar
        uses: actions/upload-artifact@v2
        with:
          name: ${{ github.event.repository.name }}
          path: ${{ github.event.repository.name }}.jar